CAM_W, CAM_H = 720, 720

# Smoothing (0..1)
JOINT_SMOOTH_ALPHA = 0.20
ANGLE_SMOOTH_ALPHA = 0.25

# Physics
# SIM_HZ = 240
# MOTOR_FORCE = 800
# POS_GAIN = 0.35
# VEL_GAIN = 1.00

# Log overlay
LOG_MAX = 12
LOG_DURATION = 6.0

# Hand openness and ArUco glove
OPEN_FINGER_EXTENDED_ON = 0.62
OPEN_FINGER_EXTENDED_OFF = 0.52
OPEN_HAND_MIN_OPEN_FINGERS = 3
OPEN_HAND_MAX_CLOSED_FINGERS = 1
OPEN_HAND_PINCH_BLOCK = 0.10
HAND_STATE_SMOOTHING = 0.20

ARUCO_GLOVE_ENABLED = True
ARUCO_DICT_NAME = "DICT_4X4_50"
ARUCO_GLOVE_FRONT_ID = 1
ARUCO_GLOVE_BACK_ID = 5
ARUCO_MARKER_SIZE_M = 0.03

# Hand tracking sensitivity
BASE_PAN_MIN = -2.5
BASE_PAN_MAX = 2.5
SHOULDER_LIFT_MIN = -2.5
SHOULDER_LIFT_MAX = 2.5
ELBOW_MIN = -2.5
ELBOW_MAX = 2.5
WRIST_FLEX_MIN = -2.5
WRIST_FLEX_MAX = 2.5
WRIST_YAW_MIN = -3.141592653589793
WRIST_YAW_MAX = 3.141592653589793
WRIST_ROLL_MIN = -3.141592653589793
WRIST_ROLL_MAX = 3.141592653589793
WRIST_PITCH_MIN = -2.5
WRIST_PITCH_MAX = 2.5

# Clap
CLAP_COOLDOWN_S = 0.6
CLAP_CLOSE_ENOUGH = 0.12
CLAP_FAST_CLOSING = 0.35

# Snap
SNAP_COOLDOWN_S = 0.5
SNAP_PINCH_ON = 0.045
SNAP_PINCH_OFF = 0.075
SNAP_FAST_RELEASE = 0.30

# Gripper mapping (thumb-index pinch)
PINCH_MIN = 0.01
PINCH_MAX = 0.95

# Reach mapping (wrist to middle MCP)
REACH_MIN = 0.05
REACH_MAX = 0.95

# Inversions
INVERT_SHOULDER_LIFT = True
INVERT_BASE_PAN = False
INVERT_ELBOW = True
INVERT_WRIST_FLEX = False
INVERT_WRIST_YAW = False
INVERT_WRIST_ROLL = False
INVERT_WRIST_PITCH = False
INVERT_GRIPPER = False

# x: hand left/right on screen
WORKSPACE_X_MIN = -0.18
WORKSPACE_X_MAX = 0.18

# y: depth/reach (farther hand -> larger y)
WORKSPACE_Y_MIN = 0.12
WORKSPACE_Y_MAX = 0.38

# z: hand up/down on screen (up -> larger z)
WORKSPACE_Z_MIN = 0.04
WORKSPACE_Z_MAX = 0.28

# IK controls
IK_MAX_ITERS = 60
IK_RESIDUAL_THRESH = 1e-4
IK_DLS_DAMPING = 0.08
IK_DLS_POSITION_GAIN = 1.0
IK_DLS_PITCH_GAIN = 0.35
IK_DLS_ORIENTATION_GAIN = 0.45
IK_DLS_CONTINUITY_GAIN = 0.08
IK_DLS_MAX_ITERS = 12
IK_DLS_MAX_STEP_RAD = 0.20

# Tool-link split for the 7-DOF chain: wrist_roll --[IK_TOOL_A_M]--> wrist_pitch --[IK_TOOL_B_M]--> EE.
# When wrist_pitch = 0, the two links lie collinear and act as the old single
# tool link of length (IK_TOOL_A_M + IK_TOOL_B_M). Defaults to a 25/25 mm split;
# measure and retune once the physical link lengths are known.
IK_TOOL_A_M = 0.025
IK_TOOL_B_M = 0.025

# Smooth target pose a bit (0..1)
POSE_SMOOTH_ALPHA = 0.25

CLOSED_TIPS_ON = 0.060
CLOSED_TIPS_OFF = 0.090

# Replace with your own file path
URDF_PATH = "/Users/ricky/PycharmProjects/ECE3161/SO-ARM100"

# Real robot control
REAL_ROBOT_ENABLE_TORQUE_LIMIT = True
REAL_ROBOT_HZ = 20.0
REAL_ROBOT_MAX_VELOCITY_DEG = 20.0
REAL_ROBOT_MAX_ACCELERATION_DEG = 50.0
REAL_ROBOT_TORQUE_LIMIT_PERCENT = 60.0
REAL_ROBOT_MAX_RELATIVE_TARGET_DEG = 4.0
REAL_ROBOT_ACTION_DEADBAND_DEG = 0.5

ENABLE_REAL_ROBOT = True
REAL_ROBOT_PORT = ""
REAL_ROBOT_ID = "my_awesome_follower_arm"

# Use the custom calibration script for the 8-motor arm rather than the stock SO101 auto-calibration flow.
# The upstream SO follower driver defaults to a 6-motor SO100/SO101 bus, so
# robot_controller.py replaces that bus with the configured motor list below.
REAL_ROBOT_AUTO_CALIBRATE = False

# Full motor order for the modified arm: 7 controllable arm DOF + gripper.
# Motor IDs must match the physical servo IDs on the Feetech daisy chain.
REAL_ROBOT_MOTOR_NAMES = [
    "shoulder_pan",
    "shoulder_lift",
    "elbow_flex",
    "wrist_flex",
    "wrist_yaw",
    "wrist_roll",
    "wrist_pitch",
    "gripper",
]
REAL_ROBOT_MOTOR_IDS = [1, 2, 3, 4, 5, 6, 7, 8]
REAL_ROBOT_MOTOR_MODEL = "sts3215"
REAL_ROBOT_MOTOR_MODELS = ["sts3215"] * len(REAL_ROBOT_MOTOR_NAMES)

# Fine-tuning offsets applied in software after the main calibration is loaded.
# Order: shoulder_pan, shoulder_lift, elbow_flex, wrist_flex, wrist_yaw, wrist_roll, wrist_pitch
# Do not include the gripper here because it is mapped separately as 0..100%.
REAL_ROBOT_JOINT_OFFSETS_DEG = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# Project-local calibration file produced by robot_calibrate.py
ROBOT_JOINT_CALIBRATION_FILE = "calibration_data/robot_joint_calibration.json"

# Optional: if you want the custom calibration script to also mirror the same JSON into
# a LeRobot cache path for an installed follower driver, set this to that full path.
# Leave empty to skip the extra copy.
LEROBOT_DRIVER_CALIBRATION_FILE = ""

CALIB_INTRINSICS_FILE = "calibration_data/calibration_intrinsics.npz"
CALIB_EXTRINSICS_FILE = "calibration_data/calibration_extrinsics.npz"
CALIB_WORKSPACE_FILE = "calibration_data/calibration_workspace.npz"

EXTRINSICS_MODE = "workspace_to_camera"

ARUCO_WORKSPACE_MIN = (-0.18, -0.12, 0.02)
ARUCO_WORKSPACE_MAX = (0.18, 0.18, 0.28)

HAND_CMD_SMOOTHING = 0.25

# Math/hand-tracking calibration source. By default this points at the project-local robot calibration generated by robot_calibrate.py.
LEROBOT_CALIBRATION_FILE = ROBOT_JOINT_CALIBRATION_FILE


# ---- Pick-and-place: object detection ----
PICKPLACE_YOLO_MODEL_PATH = "yolov8n.pt"
PICKPLACE_YOLO_DEVICE = "mps"
PICKPLACE_YOLO_INFERENCE_HZ = 8.0
PICKPLACE_YOLO_CONF_THRESHOLD = 0.45
PICKPLACE_YOLO_CLASS_WHITELIST = [
    "cup", "bottle", "apple", "orange",
    "banana", "scissors", "cell phone", "mouse",
]

# ---- Pick-and-place: top-down camera ----
PICKPLACE_CAMERA_INDEX = 1
PICKPLACE_TOPDOWN_INTRINSICS_FILE = "calibration_data/topdown_intrinsics.npz"
PICKPLACE_TOPDOWN_EXTRINSICS_FILE = "calibration_data/topdown_extrinsics.npz"
PICKPLACE_CALIB_CHESSBOARD_ROWS = 7
PICKPLACE_CALIB_CHESSBOARD_COLS = 9
PICKPLACE_CALIB_SQUARE_SIZE_M = 0.025
PICKPLACE_CALIB_MIN_INTRINSICS_CAPTURES = 12
PICKPLACE_CALIB_ANCHOR_MARKER_SIZE_M = 0.04
PICKPLACE_CALIB_ANCHOR_MARKER_DICT = "DICT_6X6_250"
PICKPLACE_CALIB_ANCHOR_MAP = [
    [0, [-0.15, 0.10, 0.00]],
    [1, [ 0.15, 0.10, 0.00]],
    [2, [-0.15, 0.30, 0.00]],
    [3, [ 0.15, 0.30, 0.00]],
]
PICKPLACE_CALIB_STABLE_FRAMES = 20
PICKPLACE_CALIB_REPROJ_WARN_PX = 3.0

# ---- Pick-and-place: drop target marker ----
PICKPLACE_DROP_MARKER_ID = 42
PICKPLACE_DROP_MARKER_DICT = "DICT_4X4_50"
PICKPLACE_DROP_MARKER_SIZE_M = 0.04

# ---- Pick-and-place: geometry ----
PICKPLACE_TABLE_Z_M = 0.02
PICKPLACE_PICK_Z_OFFSET_M = 0.005
PICKPLACE_PLACE_Z_OFFSET_M = 0.015
PICKPLACE_TRANSIT_Z_OFFSET_M = 0.08

# ---- Pick-and-place: IK / grasp orientation ----
IK_TOPDOWN_APPROACH_OFFSET_RAD = 0.05
IK_ABORT_POSITION_ERR_M = 0.010
PICKPLACE_HOME_JOINTS_RAD = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
PICKPLACE_HOME_GRIPPER_OPEN01 = 1.0

# ---- Pick-and-place: state machine ----
PICKPLACE_ARRIVAL_TOL_RAD = 0.03
PICKPLACE_WAYPOINT_DWELL_S = 0.3
PICKPLACE_GRIPPER_CLOSE_DWELL_S = 0.8
PICKPLACE_GRIPPER_OPEN_DWELL_S = 0.5
PICKPLACE_WAYPOINT_TIMEOUT_S = 8.0
PICKPLACE_MAX_ABORTS_BEFORE_ERROR = 3
PICKPLACE_CONTINUOUS_MODE = True
PICKPLACE_SCAN_DETECTION_REQUIRED_FRAMES = 2
PICKPLACE_PICKING_POLICY = "highest_confidence"

# ---- Direct Feetech calibration diagnostics/read behavior ----
# Startup chain verification is intentionally disabled so calibration does not
# appear frozen in a long serial timeout scan. Reads are checked during capture.
FEETECH_STARTUP_CHAIN_VERIFY = False

# Enable full baud scanning during capture/identify diagnostics. This is slower,
# but it proves whether IDs 1, 7, or 8 are actually at a non-1Mbps baudrate.
FEETECH_CAPTURE_FULL_BAUD_SCAN = False

# Baudrates to try when FEETECH_CAPTURE_FULL_BAUD_SCAN is enabled.
REAL_ROBOT_SCAN_BAUDRATES = [
    1000000,
    500000,
    250000,
    128000,
    115200,
    57600,
    38400,
    19200,
]

# STS3215 Present_Position is normally 56. The extra addresses are diagnostic
# fallbacks in case one servo/table variant is different.
FEETECH_PRESENT_POSITION_ADDR_CANDIDATES = [
    56,
    58,
    60,
    48,
    46,
    44,
    42,
    40,
    38,
    36,
    34,
    32,
    30,
    28,
]
FEETECH_CAPTURE_POSITION_ADDR_CANDIDATES = FEETECH_PRESENT_POSITION_ADDR_CANDIDATES

# Slightly longer reads help with long 8-motor daisy chains.
FEETECH_DIRECT_PACKET_TIMEOUT_S = 0.30
FEETECH_CAPTURE_READ_RETRIES = 6
FEETECH_CAPTURE_INTER_RETRY_S = 0.03
FEETECH_LIVE_TABLE_PERIOD_S = 0.50


# ---- No-freeze identify/calibration defaults ----
# Keep these defaults quick. Turn the full scans on only for intentional slow diagnostics.
FEETECH_STARTUP_CHAIN_VERIFY = False
FEETECH_CAPTURE_FULL_BAUD_SCAN = False
FEETECH_IDENTIFY_FULL_BAUD_SCAN = False
FEETECH_IDENTIFY_READ_RETRIES = 2
FEETECH_IDENTIFY_INTER_RETRY_S = 0.015
FEETECH_IDENTIFY_POSITION_ADDR_CANDIDATES = [56]
FEETECH_CAPTURE_READ_RETRIES = 2
FEETECH_CAPTURE_INTER_RETRY_S = 0.015
FEETECH_CAPTURE_POSITION_ADDR_CANDIDATES = [56]
FEETECH_PRESENT_POSITION_ADDR_CANDIDATES = [56]
FEETECH_DIRECT_PACKET_TIMEOUT_S = 0.18


# ---- No-freeze motor setup defaults ----
# Keep setup scans short. Turn full scans on only when a motor has an unknown ID/baud.
FEETECH_SETUP_FULL_BAUD_SCAN = False
FEETECH_SETUP_FULL_ID_SCAN = False
FEETECH_SETUP_SCAN_MAX_ID = 20
FEETECH_SETUP_EXTRA_SCAN_IDS = [0, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
FEETECH_SETUP_PROBE_TIMEOUT_S = 0.07
FEETECH_SETUP_INTER_PROBE_DELAY_S = 0.005

# Stable persistent motor-bus communication. This keeps the serial port open
# during identify/calibration instead of reopening it for every motor read.
FEETECH_STABLE_BUS_ENABLED = True
FEETECH_STABLE_BUS_PACKET_TIMEOUT_S = 0.10
FEETECH_STABLE_BUS_READ_RETRIES = 5
FEETECH_STABLE_BUS_WRITE_RETRIES = 3
FEETECH_STABLE_BUS_INTER_PACKET_DELAY_S = 0.006
FEETECH_STABLE_BUS_DRAIN_BEFORE_TX = True
FEETECH_STABLE_IDENTIFY_ATTEMPTS = 3
FEETECH_STABLE_BAUD_SWITCH_DELAY_S = 0.08



# ---- Read-only ID scan defaults ----
# Option 5 uses these settings. It never writes/flashes IDs.
FEETECH_READONLY_SCAN_MAX_ID = 20
FEETECH_READONLY_SCAN_EXTRA_IDS = [0]
FEETECH_READONLY_SCAN_FULL_BAUD_SCAN = False
FEETECH_READONLY_SCAN_READ_RETRIES = 2
FEETECH_READONLY_SCAN_SHOW_MISSES = False
# ---- Safer Feetech/ST3215 ID setup and read-only scan behavior ----
# These final assignments intentionally override earlier diagnostic defaults.
# Setup no longer trusts write status packets alone; it rescans after every ID write
# and only saves metadata after exactly the target ID responds.
FEETECH_SETUP_CONFIRM_REASSIGN_VALID_ID = True
FEETECH_SETUP_VERIFY_EXACTLY_ONE_ID = True
FEETECH_SETUP_VERIFY_RESCAN_AFTER_WRITE = True
FEETECH_SETUP_POWER_CYCLE_AFTER_ID_WRITE = False
FEETECH_SETUP_READ_RETRIES = 2
FEETECH_SETUP_WRITE_VERIFY_RETRIES = 8
FEETECH_SETUP_POST_WRITE_DELAY_S = 0.8
FEETECH_DIRECT_WRITE_RETRIES = 3

# Keep normal diagnostics fast. Turn these on only when intentionally scanning unknown hardware.
FEETECH_SETUP_FULL_BAUD_SCAN = False
FEETECH_SETUP_FULL_ID_SCAN = False
FEETECH_SETUP_SCAN_MAX_ID = 20
FEETECH_READONLY_SCAN_MAX_ID = 20
FEETECH_READONLY_SCAN_EXTRA_IDS = [0]
FEETECH_READONLY_SCAN_FULL_BAUD_SCAN = False
FEETECH_READONLY_SCAN_READ_RETRIES = 2
FEETECH_READONLY_SCAN_SHOW_MISSES = False

# Stable persistent motor-bus reads for identify/calibration.
FEETECH_STABLE_IDENTIFY_ATTEMPTS = 3
FEETECH_IDENTIFY_FULL_BAUD_SCAN = False
FEETECH_DIRECT_PACKET_TIMEOUT_S = 0.18
FEETECH_DIRECT_READ_RETRIES = 3
FEETECH_STABLE_BUS_INTER_PACKET_DELAY_S = 0.006
FEETECH_LIVE_TABLE_PERIOD_S = 0.50
# ---------------------------------------------------------------------------
# Safe one-motor ID flashing / verification
# ---------------------------------------------------------------------------
# STS/SMS/Feetech servo ID is stored in EEPROM. Unlock before writing ID and
# verify by a read-only scan afterward. The script must not trust write ACKs.
FEETECH_LOCK_REGISTER_ADDR = 55
FEETECH_LOCK_UNLOCK_VALUE = 0
FEETECH_LOCK_LOCK_VALUE = 1
FEETECH_ID_FLASH_VERIFY_RETRIES = 10
FEETECH_ID_FLASH_VERIFY_DELAY_S = 0.30
FEETECH_ID_FLASH_REQUIRE_ID_REGISTER_MATCH = True
FEETECH_ID_FLASH_LOCK_EEPROM_AFTER_WRITE = True
FEETECH_SETUP_POST_WRITE_DELAY_S = 0.80
FEETECH_SETUP_WRITE_VERIFY_RETRIES = 10